version: '3'
services:
  postgres:
    image: postgres:11.3
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    restart: "always"

  database-tests:
    build: .
    env_file:
      - config.env
    depends_on:
      - postgres
    restart: "no"
